apiVersion: v1
kind: Pod
metadata:
      labels:
        service: frontend
        api: external        
    spec:
      containers:
      - image: dockerahmedramadan/udacity-c3-frontend
        name: frontend
        imagePullPolicy: Always          
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"                
      restartPolicy: Always

